FROM golang:1.25.1
WORKDIR /app
ENV GOPROXY=https://proxy.golang.org,direct

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -gcflags "all=-N -l" -o main_debug main.go
RUN go install github.com/go-delve/delve/cmd/dlv@latest

EXPOSE 8080
EXPOSE 40000

CMD ["dlv", "exec", "./main_debug", "--headless", "--listen=:40000", "--api-version=2", "--accept-multiclient"]
