FROM golang:1.25.1 AS builder
WORKDIR /app
ENV GOPROXY=https://proxy.golang.org,direct

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main main.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]
