FROM golang:1.25 AS builder
WORKDIR /go_project

COPY go.mod go.sum ./
RUN go mod tidy && go mod download

COPY . .

RUN go build -o listener ./listener/main.go

FROM gcr.io/distroless/base-debian12
WORKDIR /go_project
COPY --from=builder /go_project/listener .
CMD ["./main"]
