FROM golang:1.25 AS builder
WORKDIR /go_project

COPY go.mod go.sum ./
RUN go mod tidy
RUN go mod download

COPY . .

RUN go build -o broadcaster ./broadcaster/main.go

FROM gcr.io/distroless/base-debian12
WORKDIR /go_project
COPY --from=builder /go_project/broadcaster ./
CMD ["./broadcaster"]
